// <auto-generated />
using System;
using ASAPMethodology.DataAccess.Concrete.EntityFramework.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASAPMethodology.DataAccess.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20230227121926_Add-InstallementAmount-To-CostOfFuture")]
    partial class AddInstallementAmountToCostOfFuture
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASAPMethodology.Entities.Concrete.CostOfFuture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CardLastName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("CardLastName");

                    b.Property<string>("CardName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("CardName");

                    b.Property<string>("Comments")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Comments");

                    b.Property<int>("DocNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DocNum");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocNum"));

                    b.Property<Guid>("ExpenseTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("InstallementAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("InstallementAmount");

                    b.Property<int>("InstallementNo")
                        .HasColumnType("int")
                        .HasColumnName("InstallementNo");

                    b.Property<string>("Methodology")
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Methodology");

                    b.Property<DateTime>("PolicyBegDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PolicyBegDate");

                    b.Property<DateTime>("PolicyEndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PolicyEndDate");

                    b.Property<int>("PolicyNum")
                        .HasColumnType("int")
                        .HasColumnName("PolicyNum");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseTypeId");

                    b.ToTable("CostOfFuture", "dbo");
                });

            modelBuilder.Entity("ASAPMethodology.Entities.Concrete.ExpenseType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("ExpenseType", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d3635a4d-a726-4e1a-900e-b58b724f1996"),
                            Name = "Sigorta"
                        },
                        new
                        {
                            Id = new Guid("fa0709bb-779f-4ba4-aa09-ea95d2a677b5"),
                            Name = "Kasko"
                        },
                        new
                        {
                            Id = new Guid("3c594c8a-fa4d-4292-bdeb-8d71d760c2f6"),
                            Name = "Kira"
                        });
                });

            modelBuilder.Entity("ASAPMethodology.Entities.Concrete.CostOfFuture", b =>
                {
                    b.HasOne("ASAPMethodology.Entities.Concrete.ExpenseType", "ExpenseType")
                        .WithMany("CostOfFutures")
                        .HasForeignKey("ExpenseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseType");
                });

            modelBuilder.Entity("ASAPMethodology.Entities.Concrete.ExpenseType", b =>
                {
                    b.Navigation("CostOfFutures");
                });
#pragma warning restore 612, 618
        }
    }
}
