// <auto-generated />
using System;
using ASAPMethodology.DataAccess.Concrete.EntityFramework.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASAPMethodology.DataAccess.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20230226155823_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASAPMethodology.Entities.Concrete.CostOfFuture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CardLastName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("CardLastName");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("CardName");

                    b.Property<string>("Comments")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Comments");

                    b.Property<int>("DocNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DocNum");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocNum"));

                    b.Property<Guid>("ExpenseTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("InstallementNo")
                        .HasColumnType("int")
                        .HasColumnName("InstallementNo");

                    b.Property<string>("Methodology")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Methodology");

                    b.Property<DateTime>("PolicyBegDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PolicyBegDate");

                    b.Property<DateTime>("PolicyEndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PolicyEndDate");

                    b.Property<int>("PolicyNum")
                        .HasColumnType("int")
                        .HasColumnName("PolicyNum");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseTypeId");

                    b.ToTable("CostOfFuture", "dbo");
                });

            modelBuilder.Entity("ASAPMethodology.Entities.Concrete.ExpenseType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("ExpenseType", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("555a09cf-9a36-42e5-8c7a-29b521e4336c"),
                            Name = "Sigorta"
                        },
                        new
                        {
                            Id = new Guid("9ee9d6dd-c409-436b-9e30-171826b3b565"),
                            Name = "Kasko"
                        },
                        new
                        {
                            Id = new Guid("148054bc-8d82-4fbb-b54e-c6f6457260e3"),
                            Name = "Kira"
                        });
                });

            modelBuilder.Entity("ASAPMethodology.Entities.Concrete.CostOfFuture", b =>
                {
                    b.HasOne("ASAPMethodology.Entities.Concrete.ExpenseType", "ExpenseType")
                        .WithMany("CostOfFutures")
                        .HasForeignKey("ExpenseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseType");
                });

            modelBuilder.Entity("ASAPMethodology.Entities.Concrete.ExpenseType", b =>
                {
                    b.Navigation("CostOfFutures");
                });
#pragma warning restore 612, 618
        }
    }
}
